input2emb_model : DescEmb # model type
model_path : false # model path if try to continue learning
embed_dim : 512     # 768 : bert-base
hidden_dim : 512    # hidden_dim 
n_heads : 8
n_layers : 4 
dropout : 0.1

sinusodial : false
text_post_proj : false
map_layers : 1 # ????
need_weights: false